#-------------------------------
# General Site Settings

title: Melissa Egan
description: //Graphic Designer//
email: egan@ualberta.ca

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Portfolio website for Graphic Designer'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Melissa believes in creating your own passion**. She recently moved from Canada to San Francisco to 
  pursue an education in Graphic Design. She loves to learn new skills that she can add to her repertoire, 
  and is constantly staying on-top of current design trends. When she is not honing her craft, Melissa is 
  out meeting new people and exploring everything the Bay Area has to offer.


skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '8'}
- {name: Learning, value: '10'}
- {name: Teamwork, value: '10'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '9'}
# - {name: Teamwork, value: '10'}
# - {name: Leadership, value: '7'}

#-------------------------------
# Work Section

projects:
- {name: Mrs. Fields & Bansky Mashup, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Rosy Reveal, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: CannaBliss Chocolate, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Schwifty Car, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fight Club Refresh, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Bottlerock Festival, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Alt | D Magazine, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Polisi Snowboarding Co., folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-marcink.jpg',
  name: 'Mykolas Marcinkevicius',
  title: 'Founder, Mico Angelo Co.',
  quote: '<p><strong>Melissa is a very talented designer</strong>
          I am genuinely impressed at the world-class design she produced 
          for our company. Her professional and collaborative style ensures
           that that everyone is on the same page throughout the entire process. 
           Whatever it is, she has it. Not to mention, she’s upbeat, helpful, and creative.
            I have worked with several designers who were good, but I would work with Melissa again over them in a heartbeat.
         </p>',
  logo: 'mico-logo.png'}



#-------------------------------
# Contact Section

social:
- {icon: 'behance', link: 'https://www.behance.net/eganbf99'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/melissa-egan-4593b24b/'}
- {icon: 'instagram', link: 'https://www.instagram.com/m_egan123/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
