#-------------------------------
# General Site Settings

title: Melissa Egan
description: //Graphic Designer//
email: egan@ualberta.ca

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Portfolio website for Graphic Designer'
  rel-author: 'https://www.linkedin.com/in/m-egan/'
  rel-publisher: 'https://www.linkedin.com/in/m-egan/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# google-analytics-ua: UA-118881352-1

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Welcome! My name is Melissa.** I am a highly creative and enthusiastic individual with over 3 years
  of marketing experience across a variety of disciplines. Most recently, I left my hometown in
   Canada and moved to San Francisco in order to pursue a career in Graphic Design. My
    business background and creative education has allowed me to garner a unique set
  of skills and experiences that I am now eager to apply in the design industry.


skills:
- {name: Communication, value: '8'}
- {name: Organization, value: '8'}
- {name: Learning, value: '10'}
- {name: Teamwork, value: '10'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '9'}
# - {name: Teamwork, value: '10'}
# - {name: Leadership, value: '7'}

#-------------------------------
# Work Section

projects:
- {name: Perceptron, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Pot Sitter App, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: CannaBliss Chocolate, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Alt | D Magazine, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Mrs. Fields Brand Revamp, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Rosy Reveal, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Schwifty Car, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Polisi Snowboarding Co., folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-marcink.jpg',
  name: 'Mykolas Marcinkevicius',
  title: 'Founder, Mico Angelo Co.',
  quote: '<p><strong>Melissa is a very talented designer.</strong>
          I am genuinely impressed at the world-class design she produced
          for our company. Her professional and collaborative style ensures
           that everyone is on the same page throughout the entire process.
           Whatever it is, she has it. Not to mention, she’s upbeat, helpful, and creative.
            I have worked with several designers who were good, but I would work with Melissa again over them in a heartbeat.
         </p>',
  logo: 'mico-logo.png'}

- {avatar: 'judy-portrait.jpg',
  name: 'Judy Doherty',
  title: 'Founder, Expression Food',
  quote: '<p><strong>Melissa is very easy to work with and I highly recommend her.</strong>
          She gave me a great package that fit my budget and exceeded all expectations with her beautiful and modern designs.
          I will definitely use her services again.
         </p>',
  logo: 'expression-food-logo.png'}



#-------------------------------
# Contact Section

social:
- {icon: 'behance', link: 'https://www.behance.net/eganbf99'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/melissa-egan-4593b24b/'}
- {icon: 'instagram', link: 'https://www.instagram.com/m_egan123/'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
